security:

    providers:
        serviceme:
            entity:
                class: FixServicemeBundle:Usuarios
                property: usuario

    encoders:
        Fix\ServicemeBundle\Entity\Usuarios:
            algorithm: bcrypt
            cost: 12

    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: serviceme
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: _usuario
                password_parameter: _contrasena
                always_use_default_target_path: true
                default_target_path: dahsboard
                csrf_token_generator: security.csrf.token_manager
                post_only: true
            
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/serviceme/*, roles: IS_AUTHENTICATED_FULLY }

        