<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * DecodificadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecodificadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
