<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * FormulariostipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulariostipoRepository extends \Doctrine\ORM\EntityRepository
{
}
