<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * FormulariosrazonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulariosrazonRepository extends \Doctrine\ORM\EntityRepository
{
}
