<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * FormulariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulariosRepository extends \Doctrine\ORM\EntityRepository
{
}
