<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * MiscTelVirtualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiscTelVirtualRepository extends \Doctrine\ORM\EntityRepository
{
}
