<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * SelectFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
