<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * ServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosRepository extends \Doctrine\ORM\EntityRepository
{
}
