<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * ServicecoreferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicecoreferenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
