<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * ServicecodetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicecodetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
