<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * servicecologRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicecologRepository extends \Doctrine\ORM\EntityRepository
{
}
