<?php

namespace Fix\ServicemeBundle\Repository;

/**
 * ServicecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicecoRepository extends \Doctrine\ORM\EntityRepository
{
}
