services:
#    fix_serviceme.example:
#        class: Fix\ServicemeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    compadre.texto:
        class: Fix\ServicemeBundle\Services\Textos