<?php

namespace Proxies\__CG__\Fix\ServicemeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \Fix\ServicemeBundle\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'usuario', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'nombres', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'apellidos', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'genero', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'fechaNacimiento', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'correo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'contrasena', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'documentoTipo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'documentoNumero', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'telefonoFijo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'telefonoMovil', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'cargo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'role', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'activo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'fechaCreado', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'fechaActualizado', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'empresa'];
        }

        return ['__isInitialized__', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'usuario', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'nombres', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'apellidos', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'genero', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'fechaNacimiento', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'correo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'contrasena', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'documentoTipo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'documentoNumero', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'telefonoFijo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'telefonoMovil', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'cargo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'role', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'activo', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'fechaCreado', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'fechaActualizado', '' . "\0" . 'Fix\\ServicemeBundle\\Entity\\Usuarios' . "\0" . 'empresa'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setfechaCreadoValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfechaCreadoValue', []);

        return parent::setfechaCreadoValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setfechaActualizadoValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfechaActualizadoValue', []);

        return parent::setfechaActualizadoValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombres($nombres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombres', [$nombres]);

        return parent::setNombres($nombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombres', []);

        return parent::getNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero($genero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', [$genero]);

        return parent::setGenero($genero);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', []);

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrasena($contrasena)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrasena', [$contrasena]);

        return parent::setContrasena($contrasena);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrasena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrasena', []);

        return parent::getContrasena();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoTipo($documentoTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoTipo', [$documentoTipo]);

        return parent::setDocumentoTipo($documentoTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoTipo', []);

        return parent::getDocumentoTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoNumero($documentoNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoNumero', [$documentoNumero]);

        return parent::setDocumentoNumero($documentoNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoNumero', []);

        return parent::getDocumentoNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoFijo($telefonoFijo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoFijo', [$telefonoFijo]);

        return parent::setTelefonoFijo($telefonoFijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoFijo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoFijo', []);

        return parent::getTelefonoFijo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil($telefonoMovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', [$telefonoMovil]);

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', []);

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo($cargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', [$cargo]);

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', []);

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreado($fechaCreado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreado', [$fechaCreado]);

        return parent::setFechaCreado($fechaCreado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreado', []);

        return parent::getFechaCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaActualizado($fechaActualizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaActualizado', [$fechaActualizado]);

        return parent::setFechaActualizado($fechaActualizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaActualizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaActualizado', []);

        return parent::getFechaActualizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\Fix\ServicemeBundle\Entity\Empresas $empresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', [$empresa]);

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

}
